
SPASS 파일을 읽기 위한 라이브러리 설치
1. pip install pyreadstat

In [ ]:
# 기본 라이브러리 호출
import pandas as pd
import numpy as np

# 시각화 라이브러리 호출
import matplotlib.pyplot as plt # 기본시각화
import seaborn as sns           # 고급시각화

In [ ]:
# 한국복지패널 제19차 가구원 데이터 SPSS형식에서 불러온다.
df = pd.read_spss("./content/koweps_hpc19_2024_beta1.sav")
df.head() # 데이터프레임 확인 상위 5개

,h19_id,h19_ind,h19_sn,h19_merkey,h_new,h_new1,h19_cobf,p19_wsc,p19_wsl,p19_wgc,...,c1907_4aq19,c1907_4aq20,c1907_4aq21,c1907_4aq22,c1907_4aq23,h19_pers_income1,h19_pers_income2,h19_pers_income3,h19_pers_income4,h19_pers_income5
0,2.0,1.0,1.0,20101.0,0.0,0.0,NaN,0.266048,0.268809,1441.082985,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1,3.0,1.0,1.0,30101.0,0.0,0.0,NaN,0.434904,0.411083,2355.716918,...,NaN,NaN,NaN,NaN,NaN,NaN,2379.0,NaN,0.0,NaN
2,4.0,1.0,1.0,40101.0,0.0,0.0,NaN,0.236213,0.223306,1279.478960,...,NaN,NaN,NaN,NaN,NaN,NaN,720.0,NaN,0.0,NaN
3,6.0,1.0,1.0,60101.0,0.0,0.0,NaN,0.554892,0.506558,3005.647871,...,NaN,NaN,NaN,NaN,NaN,3240.0,NaN,NaN,0.0,NaN
4,6.0,1.0,1.0,60101.0,0.0,0.0,NaN,0.848891,0.828363,4598.133895,...,NaN,NaN,NaN,NaN,NaN,NaN,951.0,NaN,10.0,NaN

In [23]:
raw_data = df.copy() # 원본데이터 보존을 위한 복사본 생성

In [25]:
df.info() # 데이터프레임 구조외 변수별 요약 정보 출력

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15422 entries, 0 to 15421
Columns: 1046 entries, h19_id to h19_pers_income5
dtypes: float64(1045), object(1)
memory usage: 123.1+ MB

In [26]:
df.columns # 데이터프레임에 포함된 모든 컬럼명(변수명) 확인

Index(['h19_id', 'h19_ind', 'h19_sn', 'h19_merkey', 'h_new', 'h_new1',
       'h19_cobf', 'p19_wsc', 'p19_wsl', 'p19_wgc',
       ...
       'c1907_4aq19', 'c1907_4aq20', 'c1907_4aq21', 'c1907_4aq22',
       'c1907_4aq23', 'h19_pers_income1', 'h19_pers_income2',
       'h19_pers_income3', 'h19_pers_income4', 'h19_pers_income5'],
      dtype='object', length=1046)

In [29]:
# 성별, 출생연도, 월평균임금, 직업
df[['h19_g3', 'h19_g4', 'p1902_8aq1', 'h19_eco9']]

       h19_g3  h19_g4  p1902_8aq1  h19_eco9
0         2.0  1945.0         NaN       NaN
1         1.0  1948.0       183.0     942.0
2         1.0  1942.0         NaN     782.0
3         1.0  1962.0       270.0     855.0
4         2.0  1963.0        33.0     421.0
...       ...     ...         ...       ...
15417     1.0  1975.0      1010.0     222.0
15418     2.0  1976.0       260.0     313.0
15419     2.0  2009.0         NaN       NaN
15420     1.0  1964.0         NaN     248.0
15421     2.0  1964.0         NaN       NaN

[15422 rows x 4 columns]

In [28]:
df.describe() # 수치형 변수(숫자형 컬럼)의 통계 요약 정보 확인

,h19_id,h19_ind,h19_sn,h19_merkey,h_new,h_new1,h19_cobf,p19_wsc,p19_wsl,p19_wgc,...,c1907_4aq19,c1907_4aq20,c1907_4aq21,c1907_4aq22,c1907_4aq23,h19_pers_income1,h19_pers_income2,h19_pers_income3,h19_pers_income4,h19_pers_income5
count,15422.000000,15422.000000,15422.000000,1.542200e+04,15422.000000,15422.000000,138.000000,9547.000000,9547.000000,9547.000000,...,330.000000,330.000000,330.000000,330.000000,330.000000,2844.000000,4107.000000,1075.000000,15422.000000,896.000000
mean,6101.584555,7.012450,1.005771,6.101655e+07,0.154195,0.226754,2.181159,1.000000,1.000000,5416.635487,...,2.915152,1.909091,1.803030,1.721212,2.921212,4954.102321,1664.679571,4162.537674,4.250940,1306.699777
std,3627.634224,6.766716,0.143259,3.627682e+07,0.361148,0.418746,1.617584,0.667145,0.726814,3613.678770,...,0.722256,0.793731,0.731815,0.676014,0.710220,2940.527076,1661.234908,5478.355826,65.450626,2351.891839
min,2.000000,1.000000,1.000000,2.010100e+04,0.000000,0.000000,1.000000,0.009622,0.000000,52.117115,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,-28564.000000,-148.000000,-11990.000000
25%,2969.000000,1.000000,1.000000,2.969010e+07,0.000000,0.000000,1.000000,0.483828,0.446592,2620.719401,...,2.000000,1.000000,1.000000,1.000000,3.000000,3050.000000,300.000000,1422.000000,0.000000,225.750000
50%,5676.500000,5.000000,1.000000,5.676540e+07,0.000000,0.000000,2.000000,0.921310,0.845038,4990.402553,...,3.000000,2.000000,2.000000,2.000000,3.000000,4190.000000,1196.000000,3000.000000,0.000000,532.000000
75%,9541.500000,17.000000,1.000000,9.541570e+07,0.000000,0.000000,2.000000,1.381663,1.394530,7483.966844,...,3.000000,2.000000,2.000000,2.000000,3.000000,6233.000000,2520.000000,5303.500000,0.000000,1362.250000
max,12011.000000,19.000000,9.000000,1.201117e+08,1.000000,1.000000,7.000000,3.640399,2.945577,19718.713804,...,4.000000,4.000000,4.000000,4.000000,4.000000,25168.000000,27144.000000,65000.000000,4000.000000,22000.000000